/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Interfaces;

import controladores.MarcasJpaController;
import entidades.Accesorios;
import entidades.Coches;
import entidades.Marcas;
import java.util.List;

/**
 *
 * @author Julen García
 */
public class añadirCoche extends javax.swing.JDialog {
    private menuCoches padre;
    private MarcasJpaController mc = new MarcasJpaController();
    /**
     * Creates new form añadirAcce
     * @param parent
     * @param modal
     */
    public añadirCoche(menuCoches parent, boolean modal) {
        super(parent, modal);
        padre = parent;
        initComponents();
        cargarMarcas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCancelar = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tipoMotorCoche = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        selecMarca = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        modeloCoche = new javax.swing.JTextField();
        anioCoche = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        precioCoche = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio");

        tipoMotorCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoMotorCocheActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo de motor");

        selecMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecMarcaActionPerformed(evt);
            }
        });

        jLabel6.setText("Id Marca");

        jLabel1.setText("Modelo");

        modeloCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloCocheActionPerformed(evt);
            }
        });

        anioCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioCocheActionPerformed(evt);
            }
        });

        jLabel2.setText("Año");

        precioCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioCocheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                        .addComponent(btCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(selecMarca, javax.swing.GroupLayout.Alignment.TRAILING, 0, 102, Short.MAX_VALUE)
                            .addComponent(tipoMotorCoche, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(precioCoche, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(modeloCoche, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(59, 59, 59))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                            .addComponent(anioCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addGap(58, 58, 58)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(modeloCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precioCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tipoMotorCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btGuardar))
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jLabel1)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(anioCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(219, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        // TODO add your handling code here:
        String modelo = this.modeloCoche.getText();
        int anio = Integer.parseInt(this.anioCoche.getText());
        double precio = Double.parseDouble(this.precioCoche.getText());
        String tipMotor = this.tipoMotorCoche.getText();
        String[] eleccion = this.selecMarca.getSelectedItem().toString().split(",");
        int idMarcCoche = Integer.parseInt(eleccion[0]);
        
        Coches coche = new Coches(modelo, anio, precio, tipMotor, mc.findById(idMarcCoche));
        padre.getCc().create(coche);
        this.dispose();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void tipoMotorCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoMotorCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoMotorCocheActionPerformed

    private void modeloCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloCocheActionPerformed

    private void anioCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anioCocheActionPerformed

    private void precioCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioCocheActionPerformed

    private void selecMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecMarcaActionPerformed
    private void cargarMarcas(){
        List<Marcas> marcas = this.mc.findAll();
        
        for (Marcas marca : marcas) {
            this.selecMarca.addItem(marca.getIdMarca() + ", " + marca.getNombre());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anioCoche;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField modeloCoche;
    private javax.swing.JTextField precioCoche;
    private javax.swing.JComboBox<String> selecMarca;
    private javax.swing.JTextField tipoMotorCoche;
    // End of variables declaration//GEN-END:variables
}
