/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Interfaces;

import controladores.AccesoriosJpaController;
import controladores.CochesJpaController;
import entidades.Accesorios;
import entidades.Cocheaccesorio;
import entidades.Coches;
import java.util.List;

/**
 *
 * @author Julen García
 */
public class añadirCocheAcce extends javax.swing.JDialog {
    private menuCocheAcce padre;
    private CochesJpaController cc = new CochesJpaController();
    private AccesoriosJpaController ac = new AccesoriosJpaController();
    /**
     * Creates new form añadirAcce
     * @param parent
     * @param modal
     */
    public añadirCocheAcce(menuCocheAcce parent, boolean modal) {
        super(parent, modal);
        padre = parent;
        initComponents();
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCancelar = new javax.swing.JButton();
        btGuardar = new javax.swing.JButton();
        selecCoche = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        selecAcce = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btGuardar.setText("Guardar");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        selecCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecCocheActionPerformed(evt);
            }
        });

        jLabel6.setText("Coche");

        selecAcce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecAcceActionPerformed(evt);
            }
        });

        jLabel7.setText("Accesorio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(btCancelar)
                .addGap(59, 59, 59))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selecAcce, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selecCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selecCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(selecAcce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btGuardar))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGuardarActionPerformed
        // TODO add your handling code here:
        
        String[] eleccionCoche = this.selecCoche.getSelectedItem().toString().split(",");
        int idCoche = Integer.parseInt(eleccionCoche[0]);
        String[] eleccionAcce = this.selecAcce.getSelectedItem().toString().split(",");
        int idAcce = Integer.parseInt(eleccionAcce[0]);
        
        
        Cocheaccesorio coche = new Cocheaccesorio(this.ac.findById(idAcce), this.cc.findById(idCoche));
        padre.getCac().create(coche);
        this.dispose();
    }//GEN-LAST:event_btGuardarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void selecCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecCocheActionPerformed

    private void selecAcceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecAcceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecAcceActionPerformed
  // Carga los coches y accesorios en los JComboBox de la interfaz
    private void cargarDatos(){
        List<Coches> coches = this.cc.findAll();
        List<Accesorios> accesorios = this.ac.findAll();
        for (Coches coche : coches) {
            this.selecCoche.addItem(coche.getIdCoche() + ", " + coche.getModelo());
        }
        
        for (Accesorios accesorio : accesorios) {
            this.selecAcce.addItem(accesorio.getIdAccesorio() + ", " + accesorio.getNombre());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btGuardar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> selecAcce;
    private javax.swing.JComboBox<String> selecCoche;
    // End of variables declaration//GEN-END:variables
}
