/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author Julen García
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        botonAcceder = new javax.swing.JButton();
        botonSalirInicio = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        botonAcceder1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Nirmala Text", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("Concesionario TodoMotor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 340, 60));

        botonAcceder.setBackground(new java.awt.Color(255, 204, 51));
        botonAcceder.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        botonAcceder.setForeground(new java.awt.Color(0, 0, 0));
        botonAcceder.setText("Acceder");
        botonAcceder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonAcceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAccederActionPerformed(evt);
            }
        });
        getContentPane().add(botonAcceder, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 190, 80));

        botonSalirInicio.setBackground(new java.awt.Color(255, 204, 0));
        botonSalirInicio.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        botonSalirInicio.setForeground(new java.awt.Color(0, 0, 0));
        botonSalirInicio.setText("Salir");
        botonSalirInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonSalirInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirInicioActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalirInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 190, 90));

        jLabel3.setForeground(new java.awt.Color(255, 153, 51));
        jLabel3.setText("Julen García Vázquez 1ºDAW");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/iniciov3.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 550, 430));

        botonAcceder1.setBackground(new java.awt.Color(255, 204, 51));
        botonAcceder1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        botonAcceder1.setForeground(new java.awt.Color(0, 0, 0));
        botonAcceder1.setText("Acceder");
        botonAcceder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAcceder1ActionPerformed(evt);
            }
        });
        getContentPane().add(botonAcceder1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 190, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirInicioActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirInicioActionPerformed

    private void botonAcceder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAcceder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonAcceder1ActionPerformed

    private void botonAccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAccederActionPerformed
        Opciones opciones = new Opciones();
        opciones.setLocationRelativeTo(null);
        opciones.setVisible(true);
        opciones.setResizable(false);
        this.dispose();
    }//GEN-LAST:event_botonAccederActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Inicio inicio = new Inicio();
                inicio.setLocationRelativeTo(null);
                inicio.setResizable(false);
                inicio.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAcceder;
    private javax.swing.JButton botonAcceder1;
    private javax.swing.JButton botonSalirInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
