/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import controladores.CocheaccesorioJpaController;
import entidades.Cocheaccesorio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Julen García
 */
public class menuCocheAcce extends javax.swing.JFrame {

    private CocheaccesorioJpaController cac = new CocheaccesorioJpaController();

    /**
     * Creates new form menuCocheAcce
     */
    public menuCocheAcce() {
        initComponents();
        cargarDatosJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btDelCocheAcce = new javax.swing.JButton();
        btAñadirCocheAcce = new javax.swing.JButton();
        btVolver = new javax.swing.JButton();
        btModCocheAcce = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        contCocheAcce = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Accesorios de los coches");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 400, 70));

        btDelCocheAcce.setBackground(new java.awt.Color(0, 153, 153));
        btDelCocheAcce.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btDelCocheAcce.setForeground(new java.awt.Color(0, 0, 0));
        btDelCocheAcce.setText("Quitar acce. de un coche");
        btDelCocheAcce.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btDelCocheAcce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelCocheAcceActionPerformed(evt);
            }
        });
        getContentPane().add(btDelCocheAcce, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 200, 35));

        btAñadirCocheAcce.setBackground(new java.awt.Color(0, 153, 153));
        btAñadirCocheAcce.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btAñadirCocheAcce.setForeground(new java.awt.Color(0, 0, 0));
        btAñadirCocheAcce.setText("Vincular acce. a un coche ");
        btAñadirCocheAcce.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAñadirCocheAcce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAñadirCocheAcceActionPerformed(evt);
            }
        });
        getContentPane().add(btAñadirCocheAcce, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 35));

        btVolver.setBackground(new java.awt.Color(0, 153, 153));
        btVolver.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btVolver.setForeground(new java.awt.Color(0, 0, 0));
        btVolver.setText("Volver");
        btVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 160, 35));

        btModCocheAcce.setBackground(new java.awt.Color(0, 153, 153));
        btModCocheAcce.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        btModCocheAcce.setForeground(new java.awt.Color(0, 0, 0));
        btModCocheAcce.setText("Mod. acce. de un coche");
        btModCocheAcce.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btModCocheAcce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModCocheAcceActionPerformed(evt);
            }
        });
        getContentPane().add(btModCocheAcce, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 200, 35));

        contCocheAcce.setBackground(new java.awt.Color(0, 153, 153));
        contCocheAcce.setForeground(new java.awt.Color(0, 0, 0));
        contCocheAcce.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        contCocheAcce.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jScrollPane1.setViewportView(contCocheAcce);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 380, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/taller.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDelCocheAcceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelCocheAcceActionPerformed
        // TODO add your handling code here:
        String idStr = JOptionPane.showInputDialog("Introduce la id del registro que quieras borrar.");
        try {
            int id = Integer.parseInt(idStr);

            if (id < 1) {
                JOptionPane.showMessageDialog(null, "ID inválida.");
                return;
            }

            cac.delete(id);

            cargarDatosJTable();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Por favor, introduce un número válido.");

        }
    }//GEN-LAST:event_btDelCocheAcceActionPerformed

    private void btAñadirCocheAcceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAñadirCocheAcceActionPerformed
        // TODO add your handling code here:
        añadirCocheAcce añadirCocheAcce = new añadirCocheAcce(this, true);
        añadirCocheAcce.setLocationRelativeTo(null);
        añadirCocheAcce.setResizable(false);
        añadirCocheAcce.setVisible(true);

        cargarDatosJTable();
    }//GEN-LAST:event_btAñadirCocheAcceActionPerformed

    private void btVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Opciones opciones = new Opciones();
        opciones.setLocationRelativeTo(null);
        opciones.setResizable(false);
        opciones.setVisible(true);
    }//GEN-LAST:event_btVolverActionPerformed

    private void btModCocheAcceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModCocheAcceActionPerformed
        // TODO add your handling code here:
        if (contCocheAcce.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, "No has seleccionado ningún registro");
        } else {

            modCocheAcce menuModAcceCoche = new modCocheAcce(this,true);
            menuModAcceCoche.setLocationRelativeTo(null);
            menuModAcceCoche.setResizable(false);
            menuModAcceCoche.setVisible(true);

            cargarDatosJTable();
        }
    }//GEN-LAST:event_btModCocheAcceActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarDatosJTable() {

        List<Cocheaccesorio> cocheAccelista = cac.findAll();
        String[] columnas = {"IdRegistro", "Coche", "Accesorio"};
        DefaultTableModel columnModel = new DefaultTableModel(columnas, 0);

        int numColumnas = columnModel.getColumnCount();

        Object[] fila = new Object[numColumnas];

        for (Cocheaccesorio cocheAcce : cocheAccelista) {
            int idCoche = cocheAcce.getIdCoche().getIdCoche();
            String nomCoche = cocheAcce.getIdCoche().getModelo();

            int idAcce = cocheAcce.getIdAccesorio().getIdAccesorio();
            String nomAcce = cocheAcce.getIdAccesorio().getNombre();
            fila[0] = cocheAcce.getIdRegistro();
            fila[1] = idCoche + ", " + nomCoche;
            fila[2] = idAcce + ", " + nomAcce;

            columnModel.addRow(fila);
        }
        contCocheAcce.setModel(columnModel);

    }

    public CocheaccesorioJpaController getCac() {
        return cac;
    }

    public JTable getJTable() {
        return this.contCocheAcce;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAñadirCocheAcce;
    private javax.swing.JButton btDelCocheAcce;
    private javax.swing.JButton btModCocheAcce;
    private javax.swing.JButton btVolver;
    private javax.swing.JTable contCocheAcce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
