/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Interfaces;

import controladores.MarcasJpaController;
import entidades.Coches;
import entidades.Marcas;
import java.awt.Color;
import javax.swing.JTable;

/**
 *
 * @author Julen García
 */
public class modCoche extends javax.swing.JDialog {
    private menuCoches padre;
    private Coches coche;
    private MarcasJpaController mc = new MarcasJpaController();
    /**
     * Creates new form modMarca
     * @param parent
     * @param modal
     */
    public modCoche(menuCoches parent, boolean modal) {
        super(parent, modal);
        padre = parent;
        initComponents();
        mostrarDatosEditar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        modeloCoche = new javax.swing.JTextField();
        btCancelar = new javax.swing.JButton();
        btActualizar = new javax.swing.JButton();
        anioCoche = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idCoche = new javax.swing.JTextField();
        precioCoche = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tipoMotorCoche = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        idMarcaCoche = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Modelo");

        modeloCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeloCocheActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        anioCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anioCocheActionPerformed(evt);
            }
        });

        jLabel2.setText("Año");

        jLabel3.setText("Id");

        idCoche.setEditable(false);
        idCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCocheActionPerformed(evt);
            }
        });

        precioCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                precioCocheActionPerformed(evt);
            }
        });

        jLabel4.setText("Precio");

        tipoMotorCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoMotorCocheActionPerformed(evt);
            }
        });

        jLabel5.setText("Tipo de motor");

        idMarcaCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMarcaCocheActionPerformed(evt);
            }
        });

        jLabel6.setText("Id Marca");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btActualizar)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(idCoche, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(modeloCoche, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(anioCoche, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(precioCoche, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addComponent(btCancelar)
                                .addGap(58, 58, 58))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(66, 66, 66)
                                .addComponent(idMarcaCoche))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tipoMotorCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(42, 42, 42))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modeloCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(anioCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(precioCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tipoMotorCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(idMarcaCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btActualizar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modeloCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeloCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeloCocheActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        // TODO add your handling code here:
        String modelo = modeloCoche.getText();
        int anio = Integer.parseInt(anioCoche.getText());
        double precio = Double.parseDouble(precioCoche.getText());
        String tipMotor = tipoMotorCoche.getText();
        int idMarcCoche = Integer.parseInt(this.idMarcaCoche.getText());
        
        padre.getCc().update(new Coches(coche.getIdCoche(),modelo, anio , precio, tipMotor, mc.findById(idMarcCoche)));
        mostrarDatosEditar();
        this.dispose();
    }//GEN-LAST:event_btActualizarActionPerformed

    private void anioCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anioCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anioCocheActionPerformed

    private void idCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idCocheActionPerformed

    private void precioCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precioCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precioCocheActionPerformed

    private void tipoMotorCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoMotorCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoMotorCocheActionPerformed

    private void idMarcaCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMarcaCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idMarcaCocheActionPerformed

    /**
     * @param args the command line arguments
     */
    private void mostrarDatosEditar() {
        // Obtengo el id de la persona seleccionada
        // Para ello, obtengo la fila seleccionada
        int fila = filaSeleccionadaJTable(padre.getJTable());
        // Ahora que conozco la fila puedo obtener el id de la persona
        // es el valor de la columna cero (según mi modelo) de esa fila
        int id = (int) padre.getJTable().getValueAt(fila, 0);
        // Guarda la persona seleccionada
        this.coche = padre.getCc().findById(id);
        // Muestra datos de la persona que se seleccionó en el jtable
        // en los jtextfield
        String idtext = this.coche.getIdMarca()+ "";
        String fundacion = this.coche.getAnio()+"";
        this.idCoche.setBackground(Color.GRAY);
        this.idCoche.setText(idtext);
        this.modeloCoche.setText(this.coche.getModelo());
        this.anioCoche.setText(this.coche.getPaisOrigen());
        this.precioCoche.setText(fundacion);
    }
    private int filaSeleccionadaJTable(JTable jTable1) {
        int fila = jTable1.getSelectedRow();
        return fila;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField anioCoche;
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JTextField idCoche;
    private javax.swing.JTextField idMarcaCoche;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField modeloCoche;
    private javax.swing.JTextField precioCoche;
    private javax.swing.JTextField tipoMotorCoche;
    // End of variables declaration//GEN-END:variables
}
