/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Interfaces;

import controladores.AccesoriosJpaController;
import controladores.CochesJpaController;
import entidades.Accesorios;
import entidades.Cocheaccesorio;
import entidades.Coches;
import java.awt.Color;
import java.util.List;
import javax.swing.JTable;

/**
 *
 * @author Julen García
 */
public class modCocheAcce extends javax.swing.JDialog {

    private menuCocheAcce padre;
    private Cocheaccesorio cocheAcce;
    private CochesJpaController cc = new CochesJpaController();
    private AccesoriosJpaController ac = new AccesoriosJpaController();

    /**
     * Creates new form modMarca
     *
     * @param parent
     * @param modal
     */
    public modCocheAcce(menuCocheAcce parent, boolean modal) {
        super(parent, modal);
        padre = parent;
        initComponents();
        mostrarDatosEditar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCancelar = new javax.swing.JButton();
        btActualizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        idRegistro = new javax.swing.JTextField();
        selecAcce = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        selecCoche = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        jLabel3.setText("Id");

        idRegistro.setEditable(false);
        idRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idRegistroActionPerformed(evt);
            }
        });

        selecAcce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecAcceActionPerformed(evt);
            }
        });

        jLabel7.setText("Accesorio");

        selecCoche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecCocheActionPerformed(evt);
            }
        });

        jLabel6.setText("Coche");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecAcce, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selecCoche, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btCancelar)
                            .addComponent(idRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(34, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btActualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(42, 42, 42)
                    .addComponent(jLabel7)
                    .addContainerGap(168, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(selecCoche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(selecAcce, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btActualizar))
                .addGap(24, 24, 24))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(129, 129, 129)
                    .addComponent(jLabel7)
                    .addContainerGap(82, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        // TODO add your handling code here:
        
        String[] eleccionCoche = this.selecCoche.getSelectedItem().toString().split(",");
        int idCocheElegido = Integer.parseInt(eleccionCoche[0]);
        
        String[] eleccionAcce = this.selecAcce.getSelectedItem().toString().split(",");
        int idAcceElegido = Integer.parseInt(eleccionAcce[0]);
        
        padre.getCac().update(new Cocheaccesorio(cocheAcce.getIdRegistro(), ac.findById(idAcceElegido), cc.findById(idCocheElegido)));
        mostrarDatosEditar();
        this.dispose();
    }//GEN-LAST:event_btActualizarActionPerformed

    private void idRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idRegistroActionPerformed

    private void selecAcceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecAcceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecAcceActionPerformed

    private void selecCocheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecCocheActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selecCocheActionPerformed

    /**
     * @param args the command line arguments
     */
    // Carga los datos de la marca seleccionada en la tabla y los muestra en los campos de texto

    private void mostrarDatosEditar() {
       
        int fila = filaSeleccionadaJTable(padre.getJTable());
        
        int id = (int) padre.getJTable().getValueAt(fila, 0);
        
        this.cocheAcce = padre.getCac().findById(id);
        
        String idtext = this.cocheAcce.getIdRegistro()+ "";
        
        List<Coches> coches = this.cc.findAll();
        List<Accesorios> accesorios = this.ac.findAll();
        for (Coches coche : coches) {
            this.selecCoche.addItem(coche.getIdCoche() + ", " + coche.getModelo());
        }
        
        for (Accesorios accesorio : accesorios) {
            this.selecAcce.addItem(accesorio.getIdAccesorio() + ", " + accesorio.getNombre());
        }
        this.idRegistro.setBackground(Color.GRAY);
        this.idRegistro.setText(idtext);
        int idCoche = this.cocheAcce.getIdCoche().getIdCoche();
        String nomCoche = this.cocheAcce.getIdCoche().getModelo();
        String cocheAsociado = idCoche + ", " + nomCoche;
        int idAcce = this.cocheAcce.getIdAccesorio().getIdAccesorio();
        String nomAcce = this.cocheAcce.getIdAccesorio().getNombre();
        String acceAsociado = idAcce + ", " + nomAcce;
        
        this.selecCoche.setSelectedItem(cocheAsociado);
        this.selecAcce.setSelectedItem(acceAsociado);
    }
 // Muestra los datos en los campos de texto
    private int filaSeleccionadaJTable(JTable jTable1) {
        int fila = jTable1.getSelectedRow();
        return fila;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JTextField idRegistro;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<String> selecAcce;
    private javax.swing.JComboBox<String> selecCoche;
    // End of variables declaration//GEN-END:variables
}
