/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Interfaces;

import entidades.Accesorios;
import entidades.Marcas;
import java.awt.Color;
import javax.swing.JTable;

/**
 *
 * @author Julen García
 */
public class modMarca extends javax.swing.JDialog {
    private menuMarcas padre;
    private Marcas marca;
    /**
     * Creates new form modMarca
     */
    public modMarca(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombreMarca = new javax.swing.JTextField();
        btCancelar = new javax.swing.JButton();
        btActualizar = new javax.swing.JButton();
        paisMarca = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idMarca = new javax.swing.JTextField();
        funMarca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre");

        nombreMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreMarcaActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btActualizar.setText("Actualizar");
        btActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActualizarActionPerformed(evt);
            }
        });

        paisMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paisMarcaActionPerformed(evt);
            }
        });

        jLabel2.setText("Pais de origen");

        jLabel3.setText("Id");

        idMarca.setEditable(false);
        idMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMarcaActionPerformed(evt);
            }
        });

        funMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                funMarcaActionPerformed(evt);
            }
        });

        jLabel4.setText("Fundacion");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btActualizar)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(idMarca, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(nombreMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paisMarca, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(funMarca, javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(btCancelar)
                                .addGap(58, 58, 58))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(idMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(paisMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(funMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar)
                    .addComponent(btActualizar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreMarcaActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActualizarActionPerformed
        // TODO add your handling code here:
        String nombre = nombreMarca.getText();
        String pais = paisMarca.getText();
        int fundacion = Integer.parseInt(funMarca.getText());
        padre.getMc().update(new Marcas(marca.getIdMarca(),nombre,pais,fundacion));
        mostrarDatosEditar();
        this.dispose();
    }//GEN-LAST:event_btActualizarActionPerformed

    private void paisMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paisMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paisMarcaActionPerformed

    private void idMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idMarcaActionPerformed

    private void funMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_funMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_funMarcaActionPerformed

    /**
     * @param args the command line arguments
     */
    private void mostrarDatosEditar() {
        // Obtengo el id de la persona seleccionada
        // Para ello, obtengo la fila seleccionada
        int fila = filaSeleccionadaJTable(padre.getJTable());
        // Ahora que conozco la fila puedo obtener el id de la persona
        // es el valor de la columna cero (según mi modelo) de esa fila
        int id = (int) padre.getJTable().getValueAt(fila, 0);
        // Guarda la persona seleccionada
        this.marca = padre.getMc().findById(id);
        // Muestra datos de la persona que se seleccionó en el jtable
        // en los jtextfield
        String idtext = this.marca.getIdMarca()+ "";
        String fundacion = this.marca.getFundacion()+"";
        this.idMarca.setBackground(Color.GRAY);
        this.idMarca.setText(idtext);
        this.nombreMarca.setText(this.marca.getNombre());
        this.paisMarca.setText(this.marca.getPaisOrigen());
        this.funMarca.setText(fundacion);
    }
    private int filaSeleccionadaJTable(JTable jTable1) {
        int fila = jTable1.getSelectedRow();
        return fila;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btActualizar;
    private javax.swing.JButton btCancelar;
    private javax.swing.JTextField funMarca;
    private javax.swing.JTextField idMarca;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nombreMarca;
    private javax.swing.JTextField paisMarca;
    // End of variables declaration//GEN-END:variables
}
