/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

/**
 *
 * @author Julen García
 */
public class Opciones extends javax.swing.JFrame {

    /**
     * Creates new form Opcionesv
     */
    public Opciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        botonCochesAcce = new javax.swing.JButton();
        botonMarcas = new javax.swing.JButton();
        botonAccesorios = new javax.swing.JButton();
        botonCoches = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coches.JPG"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 170, 70));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Eliga una opcion");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 220, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/subaru.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 110, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Accesorios.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, 90));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coche accesorios.PNG"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 140, 50));

        botonCochesAcce.setBackground(new java.awt.Color(102, 204, 255));
        botonCochesAcce.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonCochesAcce.setForeground(new java.awt.Color(255, 255, 255));
        botonCochesAcce.setText("Accesorios de cada coche");
        getContentPane().add(botonCochesAcce, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, 170, 50));

        botonMarcas.setBackground(new java.awt.Color(102, 204, 255));
        botonMarcas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonMarcas.setForeground(new java.awt.Color(255, 255, 255));
        botonMarcas.setText("Marcas");
        getContentPane().add(botonMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 40));

        botonAccesorios.setBackground(new java.awt.Color(102, 204, 255));
        botonAccesorios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonAccesorios.setForeground(new java.awt.Color(255, 255, 255));
        botonAccesorios.setText("Accesorios");
        getContentPane().add(botonAccesorios, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 170, 40));

        botonCoches.setBackground(new java.awt.Color(102, 204, 255));
        botonCoches.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonCoches.setForeground(new java.awt.Color(255, 255, 255));
        botonCoches.setText("Coches");
        getContentPane().add(botonCoches, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/opciones.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private void BotonAccesoriosPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        new menuAccesorios().setVisible(true);
    } 

    private void BotonCochesActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        new menuCoches().setVisible(true);
    } 
    private void BotonCochesAccerActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        new menuCocheAcce().setVisible(true);
    } 
    private void BotonMarcasActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        new menuMarcas().setVisible(true);
    } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAccesorios;
    private javax.swing.JButton botonCoches;
    private javax.swing.JButton botonCochesAcce;
    private javax.swing.JButton botonMarcas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
